export const products = [
  {
    "id": 1,
    "name": "Montelukast Sodium",
    "description": "Montelukast Sodium",
    "skuCode": "65862-567",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 2,
    "name": "TRISPEC PSE Cough Suppressant Expectorant Nasal Decongestant GRAPE Flavor",
    "description": "DEXTROMETHORPHAN HYDROBROMIDE, GUAIFENESIN, PSEUDOEPHEDRINE HYDROCHLORIDE",
    "skuCode": "58238-228",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 3,
    "name": "TOPCARE",
    "description": "ETHYL ALCOHOL",
    "skuCode": "36800-464",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 4,
    "name": "Trimethoprim",
    "description": "trimethoprim",
    "skuCode": "43386-330",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 5,
    "name": "Cashmere Always Stay-on Makeup Broad Spectrum SPF 15",
    "description": "Octinoxate, Oxybenzone, TItanium Dioxide",
    "skuCode": "68828-061",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 6,
    "name": "Felodipine",
    "description": "Felodipine",
    "skuCode": "65862-674",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 7,
    "name": "Blemish Soothing Moisturizer",
    "description": "Glycerin",
    "skuCode": "59535-6801",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 8,
    "name": "Ranitidine",
    "description": "Ranitidine",
    "skuCode": "58118-0248",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 9,
    "name": "Geodon",
    "description": "ziprasidone hydrochloride",
    "skuCode": "21695-062",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 10,
    "name": "Potassium Chloride in Dextrose and Sodium Chloride",
    "description": "DEXTROSE, SODIUM CHLORIDE, and POTASSIUM CHLORIDE",
    "skuCode": "0264-7638",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "raw",
  }, {
    "id": 11,
    "name": "Redness reliever",
    "description": "tetrahydrozoline HCl",
    "skuCode": "67510-0062",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 12,
    "name": "LBEL",
    "description": "Titanium Dioxide, Zinc Oxide, and Octinoxate",
    "skuCode": "14783-030",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 13,
    "name": "Midodrine Hydrochloride",
    "description": "midodrine hydrochloride",
    "skuCode": "51079-453",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 14,
    "name": "SILICEA",
    "description": "SILICON DIOXIDE",
    "skuCode": "10191-1822",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 15,
    "name": "Renes Cuprum",
    "description": "Renes Cuprum",
    "skuCode": "48951-8127",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 16,
    "name": "NITROGEN",
    "description": "NITROGEN",
    "skuCode": "10006-005",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 17,
    "name": "Colloidal Silver",
    "description": "Colloidal Silver",
    "skuCode": "43772-0010",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 18,
    "name": "Acid Reducer",
    "description": "Ranitidine",
    "skuCode": "21130-047",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 19,
    "name": "ATOPALM Diaper Rash",
    "description": "ZINC OXIDE",
    "skuCode": "51141-0237",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }, {
    "id": 20,
    "name": "Head and Shoulders Conditioner",
    "description": "Pyrithione Zinc",
    "skuCode": "37000-057",
    "unit": "KILOGRAM",
    "unitPrice": "100",
    "type": "final",
  }
]